source 'https://rubygems.org'
ruby '2.2.3'

###############################################################################
# Default Stuff                                                               #
###############################################################################

gem 'rails', '4.2.4'
gem 'bundler', '>= 1.8.4'
gem 'sprockets-es6'

# Database.
gem 'pg'

###############################################################################
# Assets, Views & Routes                                                      #
###############################################################################

# CSS
gem 'sass-rails'
gem 'uglifier'

# JS
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'active_model_serializers'
gem 'js-routes'
gem 'react-rails'

source 'https://rails-assets.org' do
  gem 'rails-assets-basscss'
  gem 'rails-assets-moment'
end

###############################################################################
# Environments                                                                #
###############################################################################

group :test, :development do
  gem 'dotenv-rails'
  gem 'byebug'
  gem 'faker'
end

group :development do
  gem 'pry-rails'
  gem 'spring'
  gem 'web-console', '~> 2.0'
end

group :production do
  gem 'rails_12factor'
end

gem 'metainspector'
